version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - mysql-compose-network
  app:
    image: 'app:latest'
    restart: always
    build:
      context: .
    container_name: app
    environment:
      DATASOURCE_URL: jdbc:mysql://db:3306/app?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useSSL=false
      DATASOURCE_USER: app
      DATASOURCE_PASS: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mysql-compose-network
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
